/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jrq.jrqpos;

import com.jrq.Queries.Login;
import com.jrq.Queries.Pay;
import com.jrq.Queries.Sale;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author billy
 */
public final class frmPay extends javax.swing.JDialog {

    public static ResultSet rs;
    DBConnection DBCon = new DBConnection("localhost", "3306", "jrqdb", "root", "001995234");
    Pay db = new Pay();
    Boolean PayCancel;

    /**
     * Creates new form frmPay
     */
    private final frmSale Sale;
    //frmLogin login = new frmLogin();
    //private final frmLogin login;
    public String GetID;
    String SaleID;
    String Time;
    String Date;
    private String CashAmountValue;
    double Change;
    double Cash;
    double Total;

    /**
     *
     * @param sale
     * @param Name
     */
    public frmPay(frmSale sale, String Name) {
        this.GetID = Name;
        this.Sale = sale;
        //System.out.println("frmPay received login instance: " + login);
        //System.out.println("Getter value in frmPay: " + login.getterName());
        initComponents();
        setLocationRelativeTo(null); // Center the popup on the screen
        setUndecorated(true);
        lblTotal.setText(String.valueOf((double) sale.GetTotal()));
    }

    public String getTotal() {
        return lblTotal.getText();
    }

    // Getter method to retrieve the value
    public String getInputValue() {
        return CashAmountValue;
    }

    public String GetChange() {
        return String.valueOf(Change);
    }

    public void Change() {
        CashAmountValue = txtCashAmount.getText();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        Total = Double.parseDouble(lblTotal.getText());
        Cash = Double.parseDouble(txtCashAmount.getText());
        if (Cash < Total) {
            JOptionPane.showMessageDialog(this, "Insufficient cash amount!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Change = Cash - Total;
            String message = "<html><div style='text-align:center; font-family:Arial; font-size:65px; color:Green;'>" + Change + "</div></html>";
            JOptionPane.showMessageDialog(null, message, "Change", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCashAmount = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModal(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cash Amount :");

        txtCashAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCashAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashAmountActionPerformed(evt);
            }
        });
        txtCashAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashAmountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashAmountKeyTyped(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setAutoscrolls(true);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPay.setText("Pay");
        btnPay.setAutoscrolls(true);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0.00");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTotal1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTotal1.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        Change();
        Sale.SaleID();
        Sale.AddSale();
        Sale.AddProductSold();
        Sale.UpdateStocks();
        //DefaultTableModel model = (DefaultTableModel) Sale.getJtable();
        //model.setRowCount(0);
        // System.out.println("Getter value in frmPay: " + login.getterName());
//        try {
//            DBCon.Open();
//            db.AddSale(SaleID, GetID, lblTotal.getText(), txtCashAmount.getText(), String.valueOf(Change), this.Date(), this.Time(), TItem);
//            DBCon.Close();
//        } catch (SQLException e) {
//            System.out.println(e);
//        }
        Sale.clear();
        //this.dispose();
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtCashAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashAmountActionPerformed

    private void txtCashAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashAmountKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashAmountKeyPressed

    private void txtCashAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashAmountKeyReleased

    private void txtCashAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashAmountKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JTextField txtCashAmount;
    // End of variables declaration//GEN-END:variables
}
